export const experiences = [
  {
    role: "Senior Software Engineer",
    company: "Shopee",
    period: "Feb 2024 – Present",
    bullets: [
      "Part of the Cloud Native Colocation team co-locating latency-sensitive workloads using a Kubelet-like agent deployed across 21,000 nodes in 22 Kubernetes clusters",
      "Creator and maintainer of Global Scheduler — a resource-aware scheduling orchestrator that raised cluster utilisation from ~25% to ~50%",
      "Team's presentation at KubeCon 2024",
    ],
    tech: ["Kubernetes", "Golang", "Linux", "React.js"],
  },
  {
    role: "Senior MLOps Engineer",
    company: "GoTo Financial (Gojek)",
    period: "Oct 2021 – Feb 2024",
    bullets: [
      "Maintained Data Science analytics infrastructure — JupyterHub, Airflow, Dask & MLFlow on GKE",
      "Upgraded infrastructure from single VMs to JupyterHub on GKE with Dask, cutting training cost by ~60%",
      "Principal contributor and maintainer of the internal Data Science Python library used across the team",
      "Automated batch and real-time model deployments via Gitlab CI/CD",
    ],
    tech: ["GKE", "Python", "Airflow", "MLFlow", "Gitlab", "Dask"],
  },
  {
    role: "AI Engineer",
    company: "AI Singapore",
    period: "Nov 2020 – Oct 2021",
    bullets: [
      "Led a team of 3 engineers building a multi-modal content-classification model for a regional AI startup",
      "Models: DistilUSE v2 (text), ResNet50 (image), Jodel (emoji) — combined via early/late fusion",
    ],
    tech: ["Docker", "Kubernetes", "Python", "FastAPI", "W&B", "DVC"],
  },
  {
    role: "Full Stack AI Engineer (Pro Bono)",
    company: "Idea Ink Pte Ltd",
    period: "Sep 2020 – Apr 2022",
    bullets: [
      "Ideated and built a PDF-to-infographic service served via a web application",
    ],
    tech: ["Python", "TypeScript", "Vue 3", "AWS", "FastAPI", "PostgreSQL"],
  },
  {
    role: "AI Associate Engineer",
    company: "AI Singapore",
    period: "Feb 2020 – Nov 2020",
    bullets: [
      "Built an end-to-end Recommender System for a local university library — from scoping to deployment",
    ],
    tech: ["Docker", "FastAPI", "MLFlow", "Python", "Gitlab"],
  },
  {
    role: "Data Analyst",
    company: "Nomura Singapore Limited",
    period: "Aug 2017 – Jan 2020",
    bullets: [
      "Led process automation and data analytics initiatives using Python and SQL",
      "Built Power BI and Tableau dashboards to aggregate risk data for data-driven decision-making",
    ],
    tech: ["Python", "SQL", "Power BI", "Tableau"],
  },
];

export type Project = {
  name: string;
  description: string;
  tech: string[];
  url: string | null;
  github: string | null;
  category: "app" | "open-source";
  /**
   * Set `hidden: true` to keep a project in this list but hide it from the
   * site (both the home teaser and /portfolio). Your curation switch — flip
   * weaker/experimental projects off without deleting them.
   */
  hidden?: boolean;
};

// Manually-curated projects — the source of truth for everything GitHub's API
// can't know about (private repos, custom domains, `github: null`). GitHub repos
// tagged with the `showcase` topic are merged in at build/ISR time by
// `app/projects.ts#getProjects`. Manual entries win on name/URL collisions.
export const manualProjects: Project[] = [
  {
    name: "P1 Registration Planner",
    description: "A Google-maps inspired free tool for Singapore parents navigating Primary 1 school registration.",
    tech: ["Next.js", "TypeScript", "React Leaflet", "Framer Motion", "Anthropic SDK"],
    url: "https://p1-registration.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "The Chronicle",
    description: "An OSRS-inspired productivity dashboard — journals and quest logs for real-life goals.",
    tech: ["Next.js", "Tailwind", "Electron", "Express", "macOS"],
    url: null,
    github: "https://github.com/davidcjw/the-chronicle-v2",
    category: "app",
    hidden: false,
  },
  {
    name: "ToolVault",
    description: "Free, privacy-first browser tools — convert and compress images, merge PDFs, generate QR codes and more, 100% client-side with zero uploads.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS"],
    url: "https://toolvault.davidcjw.com",
    github: "https://github.com/davidcjw/toolvault",
    category: "app",
  },
  {
    name: "HDB Floor Planner",
    description: "AI-powered 2D floor-plan editor — upload a floor plan and Claude vision traces the walls, rooms, doors and windows into editable vectors, then drag to-scale furniture over it.",
    tech: ["Next.js", "TypeScript", "Konva", "Anthropic SDK", "Supabase"],
    url: "https://hdb-floor-planner.vercel.app",
    github: null,
    category: "app",
  },
  {
    name: "SkillRank",
    description: "A daily leaderboard of the most popular Claude Code & AI-agent skills, scored from GitHub, npm and community signals and re-ranked every 24 hours.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Vitest"],
    url: "https://skill-rank-ten.vercel.app",
    github: "https://github.com/davidcjw/skill-rank",
    category: "app",
  },
  {
    name: "AlgoViz",
    description: "Learn data structures, algorithms and system design by watching them animate — 32 interactive visualizers for interview prep.",
    tech: ["Next.js", "TypeScript", "Framer Motion"],
    url: "https://algoviz.davidcjw.com",
    github: "https://github.com/davidcjw/algoviz",
    category: "app",
  },
  {
    name: "Is This AI Slop?",
    description: "Paste a URL and get a 0–100 forensic score of how AI-generated or cookie-cutter a website looks.",
    tech: ["Next.js", "TypeScript", "Framer Motion"],
    url: "https://is-this-ai-slop.davidcjw.com",
    github: "https://github.com/davidcjw/is-this-ai-slop",
    category: "app",
  },
  {
    name: "Photomind MCP",
    description: "Local-first MCP server for intelligent macOS Photos.app management — semantic search via CLIP, duplicate detection, and quality scoring.",
    tech: ["Python", "MCP", "CLIP"],
    url: null,
    github: "https://github.com/davidcjw/photomind-mcp",
    category: "open-source",
  },
  {
    name: "IPPT Calculator",
    description: "Singapore IPPT scoring calculator — computes your 2.4 km run, sit-ups, and push-ups scores with real-time results.",
    tech: ["Next.js", "TypeScript"],
    url: "https://ippt.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "One Click PDF",
    description: "Share any PDF via a URL with a simple click",
    tech: ["Next.js", "TypeScript"],
    url: "https://pdflink.app",
    github: null,
    category: "app",
  },
  {
    name: "Number Rush",
    description: "A fast-paced number game challenging your mental arithmetic speed.",
    tech: ["Vanilla js"],
    url: "https://numberrush.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "Paw Patrol Educational Game",
    description: "Your toddler's favourite pup as an educational game.",
    tech: ["Next.js", "Typescript", "Vite"],
    url: "https://pawpatrol.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "agents-md-generator",
    description: "Generate an AGENTS.md for any public GitHub repo using Claude AI — gives AI coding agents instant project context.",
    tech: ["Next.js", "TypeScript", "Claude AI"],
    url: "https://agents-md-generator.vercel.app",
    github: "https://github.com/davidcjw/agents-md-generator",
    category: "open-source",
  },
  {
    name: "SG Retirement Planner",
    description: "Singapore's most comprehensive retirement planner, including CPF",
    tech: ["Next.js", "TypeScript"],
    url: "https://sgretirementplanner.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "install-prompt",
    description: "Turn any public GitHub repo into an AI-ready installation prompt. Works with Claude, ChatGPT, Gemini, and more.",
    tech: ["Next.js", "TypeScript"],
    url: "https://install-prompt.vercel.app",
    github: "https://github.com/davidcjw/install-prompt",
    category: "open-source",
  },
  {
    name: "miles-wallet",
    description: "Track bank points and loyalty miles in one place — localStorage-based, zero backend.",
    tech: ["React", "TypeScript"],
    url: "https://miles-wallet.vercel.app",
    github: "https://github.com/davidcjw/miles-wallet",
    category: "open-source",
  },
  {
    name: "godaddy-mcp",
    description: "GoDaddy DNS MCP server — manage DNS records via natural language through AI assistants.",
    tech: ["Python", "MCP"],
    url: null,
    github: "https://github.com/davidcjw/godaddy-mcp",
    category: "open-source",
  },
  {
    name: "mcp-eval",
    description: "CI-embeddable eval harness for MCP-native agentic workflows — tool-call graph correctness and regression tracking.",
    tech: ["Python", "MCP"],
    url: null,
    github: "https://github.com/davidcjw/mcp-eval",
    category: "open-source",
  },
  {
    name: "sir-reminds-a-lot-v2",
    description: "Portable Telegram bot for credit card spend tracking and due-date reminders. SQLite-backed, Docker-deployable, zero external services.",
    tech: ["Python", "Telegram", "Docker", "SQLite"],
    url: null,
    github: "https://github.com/davidcjw/sir-reminds-a-lot-v2",
    category: "open-source",
  },
  {
    name: "a2a-inspector",
    description: "A Postman for the Agent2Agent (A2A) protocol — validate Agent Cards (spec v0.2.5) and run live tasks against any A2A agent.",
    tech: ["Next.js", "TypeScript"],
    url: "https://a2a-inspector-liart.vercel.app",
    github: "https://github.com/davidcjw/a2a-inspector",
    category: "open-source",
  },
  {
    name: "injection-testbench",
    description: "A test-bench for prompt-injection attacks and defenses — runs an attack corpus against a live Claude model, grades attack-success-rate per category, and ships a dual-LLM quarantined-data defense.",
    tech: ["Next.js", "TypeScript", "Claude AI"],
    url: "https://injection-testbench.davidcjw.com",
    github: "https://github.com/davidcjw/injection-testbench",
    category: "open-source",
  },
  {
    name: "career-copilot",
    description: "Agentic resume-tailoring and gap-analysis tool built on LangGraph, with RAG over pgvector and LangSmith observability.",
    tech: ["Python", "LangGraph", "FastAPI", "Supabase"],
    url: null,
    github: "https://github.com/davidcjw/career-copilot",
    category: "open-source",
  },

  // ── Pulled in from the wider ~/code portfolio ──────────────────────────────
  // Links inferred from your davidcjw.com domains and github.com/davidcjw/<repo>
  // pattern — verify any that are private and flip `hidden` as you like.
  {
    name: "Job Hunt Command Center",
    description: "A calm, Singapore-localised job-application tracker — Kanban board, a Today view, and stats.",
    tech: ["Next.js", "TypeScript", "Supabase"],
    url: "https://jobhunt.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "DevMind AI",
    description: "An AI-native engineering advisor built on Claude Opus.",
    tech: ["Next.js", "TypeScript", "Claude AI"],
    url: "https://devmind-ai-lilac.vercel.app",
    github: null,
    category: "app",
  },
  {
    name: "OSRS Hours to Max",
    description: "Calculates how many hours stand between you and a maxed Old School RuneScape account.",
    tech: ["Next.js", "TypeScript"],
    url: "https://osrs-hours-to-max.davidcjw.app",
    github: null,
    category: "app",
  },
  {
    name: "Democratizing Claude",
    description: "A blog and course on getting the most out of Claude Code as an engineer.",
    tech: ["Next.js", "TypeScript"],
    url: "https://democratizing-claude.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "AgentReady",
    description: "Scores any GitHub repo for AI-agent readiness (0–10) with an embeddable SVG badge.",
    tech: ["Next.js", "TypeScript"],
    url: null,
    github: "https://github.com/davidcjw/agentready",
    category: "open-source",
  },
  {
    name: "Claude's Brain",
    description: "A local dashboard that visualises which files Claude Code reads — green if present, red if missing.",
    tech: ["Next.js", "TypeScript"],
    url: null,
    github: "https://github.com/davidcjw/claude-brain",
    category: "open-source",
  },
  {
    name: "Telegram Claude Agent",
    description: "A personal Claude Code agent on your phone, via Telegram and the Claude Agent SDK.",
    tech: ["Python", "Claude Agent SDK"],
    url: null,
    github: "https://github.com/davidcjw/telegram-claude-agent",
    category: "open-source",
  },
  {
    name: "NoDoze",
    description: "A minimalist macOS menu-bar app — one toggle keeps your laptop awake while agents run.",
    tech: ["Swift", "macOS"],
    url: null,
    github: "https://github.com/davidcjw/nodoze",
    category: "open-source",
  },
  {
    name: "Jiak Simi Ah",
    description: "A Singapore food decider that settles the 'what to eat' debate in one tap.",
    tech: ["Next.js", "Google Places"],
    url: "https://jiak-simi-ah.davidcjw.com",
    github: "https://github.com/davidcjw/jiak-simi-ah",
    category: "app",
    hidden: false,
  },
  // ── Newest additions from ~/code ───────────────────────────────────────────
  {
    name: "BabyBites",
    description: "An installable PWA that randomizes age-appropriate meals for your baby and toddler — from first purées at 6 months onward, with auto grocery lists.",
    tech: ["Next.js", "TypeScript", "PWA", "Tailwind CSS"],
    url: "https://babybites.davidcjw.com",
    github: "https://github.com/davidcjw/babybites-pwa",
    category: "app",
  },
  {
    name: "Little Plates",
    description: "The family food journal — log what you cooked for the kids each day: dish, ingredients, a photo, and whether each kid gave it a YUM.",
    tech: ["Next.js", "TypeScript", "Supabase"],
    url: "https://little-plates-lyart.vercel.app",
    github: null,
    category: "app",
  },
  {
    name: "Interview Deck",
    description: "An offline PWA to revise for technical interviews — system-design topics and LeetCode patterns with spaced-repetition flashcards.",
    tech: ["React", "TypeScript", "Vite", "PWA"],
    url: "https://interview-deck.davidcjw.com",
    github: "https://github.com/davidcjw/interview-deck",
    category: "app",
  },
  {
    name: "Timesync",
    description: "A Calendly-style scheduling tool wired to Google Calendar — share a booking link or embed the widget, with Google Meet links auto-created.",
    tech: ["Next.js", "TypeScript", "Google Calendar", "OAuth"],
    url: "https://book-a-time-with-me.davidcjw.com",
    github: "https://github.com/davidcjw/timesync",
    category: "app",
  },
  {
    name: "Proof of Work",
    description: "An interactive atlas of everything I've shipped — dozens of projects rendered on a zoomable canvas, scraped straight from my repos.",
    tech: ["React", "TypeScript", "Framer Motion", "Vite"],
    url: "https://proof.davidcjw.com",
    github: "https://github.com/davidcjw/proof-of-work",
    category: "app",
  },
  {
    name: "Agent Task Board",
    description: "A local-first Kanban board for the tasks you delegate to AI coding agents — drag-and-drop cards, MCP-native, with review and Telegram hooks.",
    tech: ["Next.js", "TypeScript", "dnd-kit", "MCP"],
    url: null,
    github: "https://github.com/davidcjw/agent-task-board",
    category: "open-source",
  },
  {
    name: "RiskForge",
    description: "A production-grade, durable multi-agent portfolio-risk monitoring system — Temporal-orchestrated agents that survive restarts mid-analysis.",
    tech: ["Python", "Temporal", "FastAPI", "Claude AI"],
    url: null,
    github: "https://github.com/davidcjw/riskforge",
    category: "open-source",
  },
  {
    name: "codebrain",
    description: "A local-first, Obsidian-style graph of your ~/code folder — visualize which repos exist and how they connect.",
    tech: ["React", "Vite", "D3", "Node.js"],
    url: null,
    github: "https://github.com/davidcjw/codebrain",
    category: "open-source",
  },
  {
    name: "nlb-library-mcp",
    description: "An MCP server for Singapore's National Library Board catalogue — ask your AI assistant to find books and check which branches have them.",
    tech: ["TypeScript", "MCP", "Node.js"],
    url: null,
    github: "https://github.com/davidcjw/nlb-library-mcp",
    category: "open-source",
  },
  {
    name: "VoiceKeys",
    description: "An on-device voice-to-text keyboard for iPhone — Whisper-powered dictation with no cloud, no network, no data leaving your phone.",
    tech: ["Swift", "SwiftUI", "CoreML", "WhisperKit"],
    url: null,
    github: "https://github.com/davidcjw/voicekeys",
    category: "open-source",
  },
  {
    name: "ctxbudget",
    description: "Audit the token cost of everything your AI coding agent auto-loads on every turn (CLAUDE.md, AGENTS.md, rules) — and trim the bloat.",
    tech: ["Node.js", "CLI", "TypeScript"],
    url: null,
    github: "https://github.com/davidcjw/ctxbudget",
    category: "open-source",
  },
  {
    name: "questlog",
    description: "A zero-dependency CLI that scans a folder of git repos and flags which need attention — uncommitted changes, unpushed commits, stale branches.",
    tech: ["Node.js", "CLI"],
    url: null,
    github: "https://github.com/davidcjw/questlog",
    category: "open-source",
  },
  {
    name: "portcull",
    description: "A fast, zero-dependency CLI for the daily 'port already in use' annoyance — list and kill the process holding your port in one command.",
    tech: ["Node.js", "CLI"],
    url: null,
    github: "https://github.com/davidcjw/portcull",
    category: "open-source",
  },
  {
    name: "footprint",
    description: "Turn each day's git commits and Claude Code token spend into a shareable proof-of-work image, generated straight from your local repos.",
    tech: ["Node.js", "TypeScript", "Satori", "CLI"],
    url: null,
    github: "https://github.com/davidcjw/footprint",
    category: "open-source",
  },
  {
    name: "agentmeter",
    description: "See what your AI coding agent actually costs — a zero-dependency CLI that reports token spend and efficiency across your Claude Code sessions.",
    tech: ["Node.js", "CLI"],
    url: null,
    github: "https://github.com/davidcjw/agentmeter",
    category: "open-source",
  },
  {
    name: "agentwatch",
    description: "A live perch over your Claude Code agents — a zero-dependency terminal dashboard that shows what each running agent is doing right now.",
    tech: ["Node.js", "CLI", "TUI"],
    url: null,
    github: "https://github.com/davidcjw/agentwatch",
    category: "open-source",
  },
  {
    name: "tt-ig-downloader",
    description: "An ergonomic CLI to download TikTok and Instagram videos — single, batch, or a whole profile — built on top of yt-dlp.",
    tech: ["Python", "yt-dlp", "CLI"],
    url: null,
    github: "https://github.com/davidcjw/tt-ig-downloader",
    category: "open-source",
  },

  // ── Hidden by default — real projects without a confirmed public link, or
  //    lighter experiments. Flip `hidden` (or add a url/github) to surface them.
  {
    name: "VCP Swing Trading",
    description: "An MCP server for VCP (volatility-contraction pattern) swing-trading analysis.",
    tech: ["Python", "MCP"],
    url: null,
    github: null, // private repo — no public link yet
    category: "open-source",
    hidden: true,
  },
  {
    name: "QuoteCompare SG",
    description: "AI side-by-side comparison of interior-design renovation quotes.",
    tech: ["Next.js", "TypeScript", "Claude AI"],
    url: null,
    github: null,
    category: "app",
    hidden: true,
  },
  {
    name: "Reno Shopping List",
    description: "A renovation shopping checklist — track what to buy and where.",
    tech: ["Next.js", "Tailwind"],
    url: null,
    github: null,
    category: "app",
    hidden: true,
  },
  {
    name: "再多一个 (Zai Duo Yi Ge)",
    description: "A storefront for a Singapore homemade-tiramisu brand.",
    tech: ["Next.js", "Tailwind"],
    url: null,
    github: null,
    category: "app",
    hidden: true,
  },
  {
    name: "Ato Gelateria",
    description: "A storefront for a Singapore artisanal-gelato brand.",
    tech: ["Next.js", "Tailwind"],
    url: null,
    github: null,
    category: "app",
    hidden: true,
  },
  {
    name: "PAW Patrol Character Explorer",
    description: "A scrollytelling site exploring PAW Patrol characters — built for my son.",
    tech: ["Vite", "TypeScript"],
    url: null,
    github: null,
    category: "app",
    hidden: true,
  },
];
