export const experiences = [
  {
    role: "Senior Software Engineer",
    company: "Shopee",
    period: "Feb 2024 – Present",
    bullets: [
      "Part of the Cloud Native Colocation team co-locating latency-sensitive workloads using a Kubelet-like agent deployed across 21,000 nodes in 22 Kubernetes clusters",
      "Creator and maintainer of Global Scheduler — a resource-aware scheduling orchestrator that raised cluster utilisation from ~25% to ~50%",
      "Team's presentation at KubeCon 2024",
    ],
    tech: ["Kubernetes", "Golang", "Linux", "React.js"],
  },
  {
    role: "Senior MLOps Engineer",
    company: "GoTo Financial (Gojek)",
    period: "Oct 2021 – Feb 2024",
    bullets: [
      "Maintained Data Science analytics infrastructure — JupyterHub, Airflow, Dask & MLFlow on GKE",
      "Upgraded infrastructure from single VMs to JupyterHub on GKE with Dask, cutting training cost by ~60%",
      "Principal contributor and maintainer of the internal Data Science Python library used across the team",
      "Automated batch and real-time model deployments via Gitlab CI/CD",
    ],
    tech: ["GKE", "Python", "Airflow", "MLFlow", "Gitlab", "Dask"],
  },
  {
    role: "AI Engineer",
    company: "AI Singapore",
    period: "Nov 2020 – Oct 2021",
    bullets: [
      "Led a team of 3 engineers building a multi-modal content-classification model for a regional AI startup",
      "Models: DistilUSE v2 (text), ResNet50 (image), Jodel (emoji) — combined via early/late fusion",
    ],
    tech: ["Docker", "Kubernetes", "Python", "FastAPI", "W&B", "DVC"],
  },
  {
    role: "Full Stack AI Engineer (Pro Bono)",
    company: "Idea Ink Pte Ltd",
    period: "Sep 2020 – Apr 2022",
    bullets: [
      "Ideated and built a PDF-to-infographic service served via a web application",
    ],
    tech: ["Python", "TypeScript", "Vue 3", "AWS", "FastAPI", "PostgreSQL"],
  },
  {
    role: "AI Associate Engineer",
    company: "AI Singapore",
    period: "Feb 2020 – Nov 2020",
    bullets: [
      "Built an end-to-end Recommender System for a local university library — from scoping to deployment",
    ],
    tech: ["Docker", "FastAPI", "MLFlow", "Python", "Gitlab"],
  },
  {
    role: "Data Analyst",
    company: "Nomura Singapore Limited",
    period: "Aug 2017 – Jan 2020",
    bullets: [
      "Led process automation and data analytics initiatives using Python and SQL",
      "Built Power BI and Tableau dashboards to aggregate risk data for data-driven decision-making",
    ],
    tech: ["Python", "SQL", "Power BI", "Tableau"],
  },
];

export const projects = [
  {
    name: "IPPT Calculator",
    description: "Singapore IPPT scoring calculator — computes your 2.4 km run, sit-ups, and push-ups scores with real-time results.",
    tech: ["Next.js", "TypeScript"],
    url: "https://ippt.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "SG Retirement Planner",
    description: "Singapore's most comprehensive retirement planner, including CPF",
    tech: ["Next.js", "TypeScript"],
    url: "https://sgretirementplanner.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "One Click PDF",
    description: "Share any PDF via a URL with a simple click",
    tech: ["Next.js", "TypeScript"],
    url: "https://pdflink.app",
    github: null,
    category: "app",
  },
  {
    name: "Number Rush",
    description: "A fast-paced number game challenging your mental arithmetic speed.",
    tech: ["Vanilla js"],
    url: "https://numberrush.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "Paw Patrol Educational Game",
    description: "Your toddler's favourite pup as an educational game.",
    tech: ["Next.js", "Typescript", "Vite"],
    url: "https://pawpatrol.davidcjw.com",
    github: null,
    category: "app",
  },
  {
    name: "agents-md-generator",
    description: "Generate an AGENTS.md for any public GitHub repo using Claude AI — gives AI coding agents instant project context.",
    tech: ["Next.js", "TypeScript", "Claude AI"],
    url: "https://agents-md-generator.vercel.app",
    github: "https://github.com/davidcjw/agents-md-generator",
    category: "open-source",
  },
  {
    name: "install-prompt",
    description: "Turn any public GitHub repo into an AI-ready installation prompt. Works with Claude, ChatGPT, Gemini, and more.",
    tech: ["Next.js", "TypeScript"],
    url: "https://install-prompt.vercel.app",
    github: "https://github.com/davidcjw/install-prompt",
    category: "open-source",
  },
  {
    name: "miles-wallet",
    description: "Track bank points and loyalty miles in one place — localStorage-based, zero backend.",
    tech: ["React", "TypeScript"],
    url: "https://miles-wallet.vercel.app",
    github: "https://github.com/davidcjw/miles-wallet",
    category: "open-source",
  },
  {
    name: "photomind-mcp",
    description: "Local-first MCP server for intelligent macOS Photos.app management — semantic search via CLIP, duplicate detection, and quality scoring.",
    tech: ["Python", "MCP", "CLIP"],
    url: null,
    github: "https://github.com/davidcjw/photomind-mcp",
    category: "open-source",
  },
  {
    name: "godaddy-mcp",
    description: "GoDaddy DNS MCP server — manage DNS records via natural language through AI assistants.",
    tech: ["Python", "MCP"],
    url: null,
    github: "https://github.com/davidcjw/godaddy-mcp",
    category: "open-source",
  },
  {
    name: "mcp-eval",
    description: "CI-embeddable eval harness for MCP-native agentic workflows — tool-call graph correctness and regression tracking.",
    tech: ["Python", "MCP"],
    url: null,
    github: "https://github.com/davidcjw/mcp-eval",
    category: "open-source",
  },
  {
    name: "sir-reminds-a-lot-v2",
    description: "Portable Telegram bot for credit card spend tracking and due-date reminders. SQLite-backed, Docker-deployable, zero external services.",
    tech: ["Python", "Telegram", "Docker", "SQLite"],
    url: null,
    github: "https://github.com/davidcjw/sir-reminds-a-lot-v2",
    category: "open-source",
  },
];
